"Before analyzing anything, make sure you're solving the RIGHT problem."

In [1]:
import pandas as pd

Importing Pandas and Reading our CSV file

In [3]:
employee_data=pd.read_csv("Business_dataset.csv")

### "We have 500 employee records with 13 attributes each."

In [4]:
employee_data.shape

(500, 13)

In [5]:
employee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         500 non-null    object
 1   first_name          500 non-null    object
 2   last_name           500 non-null    object
 3   department          500 non-null    object
 4   job_title           500 non-null    object
 5   hire_date           500 non-null    object
 6   salary              480 non-null    float64
 7   city                500 non-null    object
 8   state               500 non-null    object
 9   education           500 non-null    object
 10  performance_rating  485 non-null    object
 11  years_at_company    500 non-null    float64
 12  is_remote           500 non-null    bool
dtypes: bool(1), float64(2), object(10)
memory usage: 47.5+ KB

Finding Null data

In [15]:
employee_data["salary"].isnull().sum()

np.int64(20)

In [22]:
employee_data["salary"].isna().sum()

np.int64(20)

In [10]:
employee_data.iloc[0:1]

,employee_id,first_name,last_name,department,job_title,hire_date,salary,city,state,education,performance_rating,years_at_company,is_remote
0,EMP0001,Barbara,Roberts,Engineering,Senior Engineer,2024-05-05 00:00:00,110000.0,Houston,TX,Bachelor's,Exceeds Expectations,0.7,False

In [11]:
employee_data.loc[0:1]

,employee_id,first_name,last_name,department,job_title,hire_date,salary,city,state,education,performance_rating,years_at_company,is_remote
0,EMP0001,Barbara,Roberts,Engineering,Senior Engineer,2024-05-05 00:00:00,110000.0,Houston,TX,Bachelor's,Exceeds Expectations,0.7,False
1,EMP0002,Patricia,Rodriguez,Legal,Senior Counsel,2012-07-01 00:00:00,98800.0,San Francisco,CA,Bachelor's,Exceeds Expectations,12.5,False

ANALYSIS 1: Workforce Overview
- Finding: Engineering largest dept (115 employees)

### count of employees across departments

In [12]:
employee_data.groupby("department")["employee_id"].count().sort_values(ascending=False)

department
Engineering    115
Sales          114
Finance         55
Product         53
Marketing       50
Operations      48
HR              35
Legal           30
Name: employee_id, dtype: int64

### value_counts() sorts highest to lowest by default.

In [21]:
employee_data["department"].value_counts()

department
Engineering    115
Sales          114
Finance         55
Product         53
Marketing       50
Operations      48
HR              35
Legal           30
Name: count, dtype: int64

.mean()   # average
.sum()    # total
.count()  # count
.min()    # minimum
.max()    # maximum
.median() # median

#### * size tells the Total employees; count tells you the number of non-null salaries used to calculate the mean.
* agg() stands for aggregate. In Pandas, you use it when you want to apply one or more summary calculations to grouped data.

In [9]:
employee_data.groupby("department")["salary"].agg([ "size","count", "mean"]).round(2)

             size  count       mean
department
Engineering   115    108   98565.74
Finance        55     51   89213.73
HR             35     35   67502.86
Legal          30     29   76479.31
Marketing      50     50   72350.00
Operations     48     45   71215.56
Product        53     53  103090.57
Sales         114    109   66542.20

In [7]:
employee_data.groupby("department")["salary"].agg(["count", "mean"]).round(2)

             count       mean
department
Engineering    108   98565.74
Finance         51   89213.73
HR              35   67502.86
Legal           29   76479.31
Marketing       50   72350.00
Operations      45   71215.56
Product         53  103090.57
Sales          109   66542.20

In [13]:
employee_data.groupby("department")["salary"].mean().round(2).sort_values(ascending=False)

department
Product        103090.57
Engineering     98565.74
Finance         89213.73
Legal           76479.31
Marketing       72350.00
Operations      71215.56
HR              67502.86
Sales           66542.20
Name: salary, dtype: float64

In [6]:
employee_data["department"] == "Product"

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: department, Length: 500, dtype: bool

In [7]:
employee_data[employee_data["department"] == "Product"]["job_title"].unique()

array(['Product Manager', 'Senior PM', 'VP of Product', 'Product Analyst'],
      dtype=object)

ANALYSIS 2: Salary Band Analysis  
- Finding: Product highest avg salary $103,090
- Insight: Justified by senior role concentration

#### Layer 1 — Filter: give me only Product department rows
employee_data[employee_data["department"] == "Product"]

#### Layer 2 — Group: within those rows, group by job title
.groupby("job_title")

#### Layer 3 — Count: how many employee IDs in each title
["employee_id"].count()

#### Layer 4 — Sort: highest count first
.sort_values(ascending=False)

In [18]:
employee_data[employee_data["department"] == "Product"].groupby("job_title")["employee_id"].count().sort_values(ascending=False)

job_title
Senior PM          17
VP of Product      14
Product Manager    12
Product Analyst    10
Name: employee_id, dtype: int64

In [21]:
employee_data[employee_data["department"] == "Product"]["job_title"].value_counts()

job_title
Senior PM          17
VP of Product      14
Product Manager    12
Product Analyst    10
Name: count, dtype: int64

In [32]:
employee_data[
    employee_data["department"] == "Product"
]["performance_rating"].value_counts()

performance_rating
Meets Expectations      21
Exceeds Expectations    18
Outstanding              7
Needs Improvement        5
Name: count, dtype: int64

In [33]:
employee_data[
    (employee_data["department"] == "Product") &
    (employee_data["performance_rating"] == "Exceeds Expectations")
].groupby("job_title")["employee_id"].count().sort_values(ascending=False)

job_title
Senior PM          7
VP of Product      6
Product Manager    3
Product Analyst    2
Name: employee_id, dtype: int64

In [34]:
employee_data[
    (employee_data["department"] == "Product") &
    (employee_data["performance_rating"] == "Meets Expectations")
].groupby("job_title")["employee_id"].count().sort_values(ascending=False)

job_title
Senior PM          10
VP of Product       5
Product Analyst     4
Product Manager     2
Name: employee_id, dtype: int64

In [35]:
employee_data[
    (employee_data["department"] == "Product") &
    (employee_data["performance_rating"] == "Outstanding")
].groupby("job_title")["employee_id"].count().sort_values(ascending=False)

job_title
Product Manager    3
Product Analyst    2
VP of Product      2
Name: employee_id, dtype: int64

In [36]:
employee_data[
    (employee_data["department"] == "Product") &
    (employee_data["performance_rating"] == "Needs Improvement")
].groupby("job_title")["employee_id"].count().sort_values(ascending=False)

job_title
Product Manager    3
Product Analyst    2
Name: employee_id, dtype: int64

Single [] for filtering rows — double [[]] is for selecting multiple columns.

In [14]:
edu_data =employee_data[["department","employee_id","education"]] ### slicing only necessary columns/attributes

In [15]:
edu_data

      department employee_id    education
0    Engineering     EMP0001   Bachelor's
1          Legal     EMP0002   Bachelor's
2             HR     EMP0003   Bachelor's
3        Finance     EMP0004  Associate's
4          Sales     EMP0005   Bachelor's
..           ...         ...          ...
495  Engineering     EMP0496     Master's
496      Finance     EMP0497   Bachelor's
497        Sales     EMP0498     Master's
498        Legal     EMP0499     Master's
499        Legal     EMP0500  High School

[500 rows x 3 columns]

In [9]:
employee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         500 non-null    object
 1   first_name          500 non-null    object
 2   last_name           500 non-null    object
 3   department          500 non-null    object
 4   job_title           500 non-null    object
 5   hire_date           500 non-null    object
 6   salary              480 non-null    float64
 7   city                500 non-null    object
 8   state               500 non-null    object
 9   education           500 non-null    object
 10  performance_rating  485 non-null    object
 11  years_at_company    500 non-null    float64
 12  is_remote           500 non-null    bool
dtypes: bool(1), float64(2), object(10)
memory usage: 47.5+ KB

In [10]:
salary_data =employee_data[["department","salary"]]
salary_data   ### slicing only the necessary columns/attributes

      department    salary
0    Engineering  110000.0
1          Legal   98800.0
2             HR   66800.0
3        Finance   97900.0
4          Sales   73100.0
..           ...       ...
495  Engineering   57500.0
496      Finance  143000.0
497        Sales   45600.0
498        Legal   77600.0
499        Legal   69100.0

[500 rows x 2 columns]

In [12]:
salary_data.groupby("department")["salary"].agg(["count", "min","max","mean"]).round(2)

             count      min       max       mean
department
Engineering    108  57300.0  166100.0   98565.74
Finance         51  58100.0  143000.0   89213.73
HR              35  37400.0  110100.0   67502.86
Legal           29  54400.0  107600.0   76479.31
Marketing       50  42400.0  120400.0   72350.00
Operations      45  41300.0  121400.0   71215.56
Product         53  63100.0  155800.0  103090.57
Sales          109  44200.0  111900.0   66542.20

In [14]:
# Store your result first
result = salary_data.groupby("department")["salary"].agg(["size" ,"min","max","mean"]).round(2)

# Then create a new gap column
result["gap"] = result["max"] - result["min"]

# Then sort by gap
result.sort_values("gap", ascending=False)

             size      min       max       mean       gap
department
Engineering   115  57300.0  166100.0   98565.74  108800.0
Product        53  63100.0  155800.0  103090.57   92700.0
Finance        55  58100.0  143000.0   89213.73   84900.0
Operations     48  41300.0  121400.0   71215.56   80100.0
Marketing      50  42400.0  120400.0   72350.00   78000.0
HR             35  37400.0  110100.0   67502.86   72700.0
Sales         114  44200.0  111900.0   66542.20   67700.0
Legal          30  54400.0  107600.0   76479.31   53200.0

In [17]:
employee_count=salary_data["department"].value_counts()
employee_count

department
Engineering    115
Sales          114
Finance         55
Product         53
Marketing       50
Operations      48
HR              35
Legal           30
Name: count, dtype: int64

In [23]:
Total_payroll=salary_data.groupby("department")["salary"].agg(["size","count" ,"sum"]).round(2)
Total_payroll

             size  count         sum
department
Engineering   115    108  10645100.0
Finance        55     51   4549900.0
HR             35     35   2362600.0
Legal          30     29   2217900.0
Marketing      50     50   3617500.0
Operations     48     45   3204700.0
Product        53     53   5463800.0
Sales         114    109   7253100.0

ANALYSIS 3: Talent Retention Risk
- Finding: 11 Outstanding Sales staff underpaid
- Insight: Critical poaching risk — immediate action needed
- Recommendation: Urgent salary review before Q3

In [24]:
Total_payroll.sum()

size          500.0
count         480.0
sum      39314600.0
dtype: float64

In [26]:
employee_data[employee_data["department"] == "Sales"].groupby("department")["salary"].mean()

department
Sales    66542.201835
Name: salary, dtype: float64

In [27]:
employee_data[employee_data["department"] == "Sales"]["salary"].mean()

np.float64(66542.20183486238)

"Which department has the highest remote work percentage? Does that make business sense to you?"

In [48]:
(employee_data.groupby("department")["is_remote"].mean()*100).round(2).sort_values(ascending=False)

department
HR             37.14
Legal          36.67
Sales          35.09
Finance        34.55
Product        33.96
Engineering    33.91
Marketing      32.00
Operations     27.08
Name: is_remote, dtype: float64

In [52]:
company_average_salary = employee_data["salary"].mean().round(1)
company_average_salary

np.float64(81905.4)

In [51]:
company_average_salary

np.float64(81905.41666666667)

In [73]:
Talent_Retention_data = employee_data[["employee_id", "first_name", "last_name", "department", "salary", "performance_rating"]]

In [74]:
OS_perfo= Talent_Retention_data[(Talent_Retention_data["performance_rating"] == "Outstanding") 
    & (Talent_Retention_data["salary"]>company_average_salary)].sort_values("salary",ascending=False)
OS_perfo

    employee_id first_name last_name   department    salary performance_rating
453     EMP0454    Kenneth     Smith      Product  153900.0        Outstanding
245     EMP0246   Jennifer    Flores      Product  153400.0        Outstanding
286     EMP0287     Ashley     Perez  Engineering  153000.0        Outstanding
455     EMP0456      Betty    Harris  Engineering  145800.0        Outstanding
97      EMP0098      Kevin     Davis  Engineering  138200.0        Outstanding
101     EMP0102    William  Martinez      Finance  123100.0        Outstanding
437     EMP0438       Mark     Lopez   Operations  120900.0        Outstanding
94      EMP0095  Stephanie       Lee   Operations  120500.0        Outstanding
355     EMP0356      David      King      Finance  120300.0        Outstanding
13      EMP0014       Mark  Anderson    Marketing  119700.0        Outstanding
310     EMP0311    Timothy    Rivera  Engineering  117200.0        Outstanding
392     EMP0393       John  Williams  Engineering  113300.0        Outstanding
255     EMP0256    Matthew  Gonzalez  Engineering  112400.0        Outstanding
353     EMP0354    Deborah     Brown        Sales  109600.0        Outstanding
338     EMP0339   Jennifer    Walker  Engineering  107000.0        Outstanding
127     EMP0128      Sarah  Robinson      Product  103800.0        Outstanding
183     EMP0184    Michael     Allen      Product  102000.0        Outstanding
439     EMP0440    Melissa     Green        Sales  101800.0        Outstanding
465     EMP0466      Donna     Smith  Engineering  101400.0        Outstanding
268     EMP0269     George    Walker  Engineering  101000.0        Outstanding
8       EMP0009     Amanda    Martin      Finance  100800.0        Outstanding
187     EMP0188    Barbara  Williams  Engineering   99500.0        Outstanding
33      EMP0034      Nancy    Nguyen      Product   99300.0        Outstanding
106     EMP0107      Susan    Flores  Engineering   97600.0        Outstanding
402     EMP0403     Andrew  Williams  Engineering   97000.0        Outstanding
193     EMP0194    William      King      Finance   85400.0        Outstanding
352     EMP0353     Joshua    Thomas      Finance   84700.0        Outstanding

In [75]:
OS_perfo["department"].value_counts()

department
Engineering    12
Product         5
Finance         5
Operations      2
Sales           2
Marketing       1
Name: count, dtype: int64

In [76]:
OS_perfo= Talent_Retention_data[(Talent_Retention_data["performance_rating"] == "Outstanding") 
    & (Talent_Retention_data["salary"]<company_average_salary)].sort_values("salary",ascending=False)
OS_perfo["department"].value_counts()

department
Sales          11
Engineering    10
Marketing       7
Operations      5
Legal           2
Product         2
Finance         1
HR              1
Name: count, dtype: int64